filter:
    paths: ["src/*"]

build:
    environment:
        docker: true
        php:
            version: 5.5.25
    tests:
        before:
            - git clone https://github.com/jmartin82/mmock.git
            - docker build mmock -t jordimartin/mmock
            - docker run -d -v $PWD/ops/docker/mmock/config:/config -p 8082:8082 -p 8083:8083 jordimartin/mmock
            - echo '127.0.0.1 mmock' >> /etc/hosts
        override:
            - 
                command: ./bin/http tests:run clover
                coverage:
                    file: ./bin/clover.xml
                    format: clover
            - ./ops/scripts/scrutinizer.unit.sh
            - ./ops/scripts/scrutinizer.integration.sh