version: '2'

services:
  mmock:
      image: jordimartin/mmock:latest
      ports:
        - "8082:8082"
        - "8083:8083"
      volumes:
        - ./mmock/config:/config
  phpfarm:
      build: phpfarm
      volumes:
        - ../../:/app/http-client
      links:
        - mmock